name: Automated Build

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Build document
      run: |
        latexmk -g -f --interaction=nonstopmode
        cp out/main.pdf out/${{ github.event.repository.name }}.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LaTeX-Output
        path: out/
    - name: Check release tag
      id: check_tag
      if: github.event_name != 'pull_request'
      run: echo "build_tag=$(git tag -l build)" >> $GITHUB_OUTPUT
    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      if: ${{ steps.check_tag.outputs.build_tag == 'build' }}
      with:
        tag_name: build
        files: out/${{ github.event.repository.name }}.pdf